-- CreateTable
CREATE TABLE `Usuario` (
    `USUA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USUA_Nome` VARCHAR(125) NOT NULL,
    `USUA_Email` VARCHAR(125) NOT NULL,
    `USUA_Senha` VARCHAR(255) NOT NULL,

    PRIMARY KEY (`USUA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `UsuarioAutenticacao` (
    `TWFA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `USUA_ID` INTEGER NOT NULL,
    `TWFA_Codigo` VARCHAR(255) NULL,
    `TWFA_Verificador` VARCHAR(255) NULL,
    `TWFA_DataExpiracao` DATETIME(3) NOT NULL,
    `TWFA_DataCriacao` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `TWFA_DataAtualizacao` DATETIME(3) NOT NULL,

    PRIMARY KEY (`TWFA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Modalidade` (
    `MODL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MODL_Nome` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`MODL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Aula` (
    `AULA_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `MODL_ID` INTEGER NOT NULL,
    `Observacao` LONGTEXT NULL,
    `AULA_Data` DATETIME NOT NULL,
    `STAL_ID` INTEGER NOT NULL,

    PRIMARY KEY (`AULA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `StatusAula` (
    `STAL_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `STAL_Nome` VARCHAR(100) NOT NULL,

    PRIMARY KEY (`STAL_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `Aluno` (
    `ALUN_ID` INTEGER NOT NULL AUTO_INCREMENT,
    `ALUN_Nome` VARCHAR(255) NOT NULL,
    `ALUN_Altura` INTEGER NOT NULL,
    `ALUN_Peso` DECIMAL(5, 2) NOT NULL,
    `ALUN_Lesao` VARCHAR(255) NULL,
    `ALUN_Email` VARCHAR(255) NULL,
    `ALUN_Telefone` VARCHAR(255) NULL,
    `ALUN_CPF` VARCHAR(255) NULL,
    `ALUN_DataNascimento` DATE NULL,
    `ALUN_Objetivo` VARCHAR(255) NULL,
    `ALUN_IndicacaoMedica` VARCHAR(255) NULL,
    `ALUN_NomeImagem` LONGTEXT NULL,
    `ALUN_Base64Imagem` LONGTEXT NULL,
    `ALUN_Ativo` BOOLEAN NOT NULL DEFAULT true,

    PRIMARY KEY (`ALUN_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `AlunoAula` (
    `ALUN_ID` INTEGER NOT NULL,
    `AULA_ID` INTEGER NOT NULL,

    PRIMARY KEY (`ALUN_ID`, `AULA_ID`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `UsuarioAutenticacao` ADD CONSTRAINT `UsuarioAutenticacao_USUA_ID_fkey` FOREIGN KEY (`USUA_ID`) REFERENCES `Usuario`(`USUA_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Aula` ADD CONSTRAINT `Aula_MODL_ID_fkey` FOREIGN KEY (`MODL_ID`) REFERENCES `Modalidade`(`MODL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `Aula` ADD CONSTRAINT `Aula_STAL_ID_fkey` FOREIGN KEY (`STAL_ID`) REFERENCES `StatusAula`(`STAL_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AlunoAula` ADD CONSTRAINT `AlunoAula_ALUN_ID_fkey` FOREIGN KEY (`ALUN_ID`) REFERENCES `Aluno`(`ALUN_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE `AlunoAula` ADD CONSTRAINT `AlunoAula_AULA_ID_fkey` FOREIGN KEY (`AULA_ID`) REFERENCES `Aula`(`AULA_ID`) ON DELETE RESTRICT ON UPDATE CASCADE;
